### ISSUE TITLE
Implement more functionalities through classes - Something to work on before moving to ELO

### ISSUE THREAD

**Issue by TheUltimateKeval** [PugBotDevs/PugBot#12]
1) Add a `user` property to `Pugger` class to store a `Discord.User` instance for the pugger. (Helpful in DMing on game start and stuff)
2) Instead of just passing the channel ID, use `Game.channel` and `Pickups.channel` to store a complete `Discord.TextChannel`. (Useful for the next step)
3) Implement the `readyHandler` and `matchMaker` as methods of the Game class. (Makes it easier to access handlers without having to import dependencies

I won't be able to work much on the bot myself due to exams and stuff so I'll just try to point out stuff in which things can be made better :P

Edit:
4) Also store `Pugger` instances instead of IDs in `Game.members`, ` Game.notReadyMembers` and `Game.teams`.

**Comment by PsiAphex** [comment]
Alright
