### ISSUE TITLE
No way to differentiate and update pickup options which are inherited from a channel

### ISSUE THREAD

**Issue by TheUltimateKeval** [PugBotDevs/PugBot#20]
The current system of serializing Pickups data simply inherits channel default options and then overrides them with additional configuration specific to that Pickups and then stores it as a property. However, this provides no way to update inherited properties without reloading the cache from the database.

I could figure out two possible ways to tackle this issue -

First, where we make changes to the Class structures where we use getters to dynamically return a Pickup's configuration. This will require storing the channel default options separately.

Second, we directly update the database when changes are made to channel options and then execute an update from database method on all Pickups instances which inherit from that channel, only updating necessary properties instead of serializing the whole data into Pickups instances.

I need suggestions and opinions about which one to use or if any other more efficient and simpler method can be used.
This also calls for the need to store pickup channel data in a more structured and meaningful manner like having its own class.

**Comment by PsiAphex** [comment]
AFAIK, Pickups.opts is the full perms including inherited perms, realOpts is the real perms without inherition and thats what is being stored in the database, realOpts contains default over rides + channel defaults, we can update inherited properties by directly just changing it in cache and then implement some changeProperties method in Pickups which updates channel specific overrides

**Comment by PsiAphex** [comment]
But I suppose we could stop uploading defaults to the DB and leave channel settings empty on creation and assign defaults to the channel on local initialization

**Comment by TheUltimateKeval** [comment]
> AFAIK, Pickups.opts is the full perms including inherited perms, realOpts is the real perms without inherition and thats what is being stored in the database, realOpts contains default over rides + channel defaults, we can update inherited properties by directly just changing it in cache and then implement some changeProperties method in Pickups which updates channel specific overrides

But that feels janky and inconsistent. Having a better system for storing and accessing options is necessary.
